<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Blog_model extends CI_Model
{

    public $table = 'tb_blog_tag';
    public $id = 'tagID';
    public $table2 = 'tb_blog';
    public $id2 = 'blogID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

   
    // get all
    function get_all()
    {
        $this->db->order_by($this->id2, $this->order);
        return $this->db->get($this->table2)->result();
    }

    function get_all2()
    {
        $this->db->select("tb_blog.*, tb_blog_tag.name");
        $this->db->join('tb_blog_tag', 'tb_blog.tagID = tb_blog_tag.tagID');
        $query = $this->db->get($this->table2);
        return $query->result();

    }

    // function get_all2()
    // {
    //     $this->db->select('tb_training.*, tb_training_category.name');
    //     $this->db->join('tb_training_category', 'tb_training.category_id = tb_training_category.category_id');
    //     $this->db->order_by($this->id, $this->order);
    //     return $this->db->get($this->table2)->result();
    // }

    // get data by id
    function get_by_id($id2)
    {
        $this->db->where($this->id2, $id2);
        return $this->db->get($this->table2)->row();
    }

//get category data
    function get_tag()
    {
        $query = $this->db->get($this->table);
        return $query->result();
    }
//for tag table
    function insert($data)
    {
        $this->db->insert($this->table, $data);

    }
//for blog table
    function insert2($data)
    {
        $this->db->insert($this->table2, $data);

    }

    // update tag data
    // function update($id, $data)
    // {
    //     $this->db->where($this->id, $id);
    //     $this->db->update($this->table, $data);
    // }
// update blog data
    function update_2($id, $data)
    {
        $this->db->where($this->id2, $id);
        return $this->db->update($this->table2, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id2, $id);
        $this->db->delete($this->table2);
    }
    function delete_2($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Blood_group_model.php */
/* Location: ./application/models/Blood_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-01 14:53:53 */
/* http://harviacode.com */