<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Gallery_category_model extends CI_Model
{

    public $table = 'tb_gallery_category';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {

        return $this->db->get($this->table)->result();
    }
    
    // get category
    function get_category()
    {
        $this->db->select('tb_gallery_category.*');
         $this->db->order_by('tb_gallery_category.id', 'DESC');
         return $this->db->get('tb_gallery_category')->result();
    }
    

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    function exist_category($id)
    {
        $this->db->where('name', $id);
        return $this->db->get($this->table)->row();
    }
    

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Blood_group_model.php */
/* Location: ./application/models/Blood_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-01 14:53:53 */
/* http://harviacode.com */