<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Setting_model extends CI_Model
{

    public $table = 'tb_settings';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }
    
    function get_all()
    {
    return $this->db->get($this->table)->row();
    }
    
     function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Enrollee_model.php */
/* Location: ./application/models/Enrollee_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-06 18:15:49 */
/* http://harviacode.com */
