<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Trainings_model extends CI_Model
{

    public $table = 'tb_training_category';
    public $id = 'category_id';
    public $table2 = 'tb_training';
    public $id2 = 'trainingID';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

   
    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_all2()
    {
        $this->db->select("tb_training.*, tb_training_category.name");
        $this->db->join('tb_training_category', 'tb_training.category_id = tb_training_category.category_id');
        $query = $this->db->get($this->table2);
        return $query->result();

    }

    // function get_all2()
    // {
    //     $this->db->select('tb_training.*, tb_training_category.name');
    //     $this->db->join('tb_training_category', 'tb_training.category_id = tb_training_category.category_id');
    //     $this->db->order_by($this->id, $this->order);
    //     return $this->db->get($this->table2)->result();
    // }

    // get data by id
    function get_by_id($id2)
    {
        $this->db->where($this->id, $id2);
        return $this->db->get($this->table2)->row();
    }

//get category data
    function get_category()
    {
        $query = $this->db->get($this->table);
        return $query->result();
    }

    function insert($data)
    {
        $this->db->insert($this->table, $data);

    }

    function insert2($data)
    {
        $this->db->insert($this->table2, $data);

    }
    public function insert3($data)
    {
        return $this->db->insert('fc_events_table', $data);
    }

    

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    function update_2($id, $data)
    {
        $this->db->where($this->id, $id);
        return $this->db->update('fc_events_table', $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    function delete_2($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
}

/* End of file Blood_group_model.php */
/* Location: ./application/models/Blood_group_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-01 14:53:53 */
/* http://harviacode.com */