<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Cv extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Cv_model', 'Audit_model']);
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        $page_data = $this->Cv_model->get_all();

        $data = array(
            'title' => 'Cv',
            'cv_data' => $page_data,
        );

        $this->template->load('admin', 'cv/list', $data);

    }

    public function delete($id)
    {
      //  $this->check_role(); 
        $row = $this->Cv_model->get_by_id($id);

        if ($row) {
            $this->Cv_model->delete($id);
            $task = 'Deleted a cv from cv table';
            $this->audit($task);
            $this->session->set_flashdata('message', 'cv deleted Successfully');
            redirect(site_url('cv'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('cv'));
        }
    }

    public function audit($task)
    {
        $login = $this->session->userdata('logged_in');
        $user = $login['firstname'] . ' ' . $login['lastname'];
        $data_audit = array(
            'user' => $user,
            'task' => $task,
            'date_time' => date('Y-m-d H:i:s', time()),
        );

        $this->Audit_model->insert($data_audit);
    }

}

/* End of file Blood_group.php */
/* Location: ./application/controllers/Blood_group.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-01 14:53:53 */
/* http://harviacode.com */
