<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Feedback extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model(['Feedback_model', 'Audit_model']);
        $this->load->library('form_validation');
        $this->load->library('datatables');
    }

    public function index()
    {
        // $page_data = $this->Feedback_model->get_all();
        $page_data = $this->Feedback_model->get_all();

        $data = array(
            'title' => 'Feedback',
            'feedback_data' => $page_data,
        );

        $this->template->load('admin', 'feedback/list', $data);

    }

    public function create()
    {
        $data = array(
            'title' => 'Feedback',
            'button' => 'Add Feedback',
        );
        $this->template->load('admin', 'feedback/form', $data);
    }


    public function create_action()
    {
        $this->_rules();

        if ($this->form_validation->run() == false) {
            $this->create();
        } else {

            $cont = $this->input->post('content');
            $data = array(
                'name' => $this->input->post('name', true),
                'email' => $this->input->post('email', true),
                'message' => $this->input->post('message', true),
            );
            $this->Feedback_model->insert($data);
            // $task='Added '. $this->input->post('name',TRUE).' to Blood Group';
            $task = 'Added ' . $this->input->post('name') . ' to webpage table';
            $this->audit($task);
            $this->session->set_flashdata('message', 'Feedback created successfully');
            redirect(site_url('feedback'));
        }
    }


    public function edit($id)
    {
        $row = $this->Feedback_model->get_by_id($id);
        if ($row) {
            $data = array(
                'button' => 'Update',
                'title' => 'Update Feedback',
                'action' => site_url('feedback/edit_action'),
                'id' => set_value('id', $row->feedback_id),
                'name' => set_value('name', $row->name),
                'email' => set_value('email', $row->email),
                'message' => set_value('message', html_entity_decode($row->message)),
            );
            $this->template->load('admin', 'feedback/edit', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('feedback'));
        }
    }

    public function edit_action()
    {
        $data = array(
            'name' => $this->input->post('name', true),
            'email' => $this->input->post('email', true),
            'message' => $this->input->post('message', true),
        );
        $this->Feedback_model->update($this->input->post('id', true), $data);
        // $task='Updated '. $this->input->post('name',TRUE).' on Blood Group';
       // $this->audit($task);
        $task = 'Updated ' . $this->input->post('name') . ' page on webpage table';
        $this->audit($task);
        $this->session->set_flashdata('message', 'Feedback updated successfully');
        redirect(site_url('feedback'));
    }

    public function delete($id)
    {
      //  $this->check_role(); 
        $row = $this->Feedback_model->get_by_id($id);

        if ($row) {
            $this->Feedback_model->delete($id);
            $task = 'Deleted a feedback from Feedback table';
            $this->audit($task);
            $this->session->set_flashdata('message', 'feedback deleted Successfully');
            redirect(site_url('feedback'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('feedback'));
        }
    }

    public function audit($task)
    {
        $login = $this->session->userdata('logged_in');
        $user = $login['firstname'] . ' ' . $login['lastname'];
        $data_audit = array(
            'user' => $user,
            'task' => $task,
            'date_time' => date('Y-m-d H:i:s', time()),
        );

        $this->Audit_model->insert($data_audit);
    }

    public function _rules()
    {
        $this->form_validation->set_rules(
            'name',
            'name',
            'trim|required'
        );
        $this->form_validation->set_rules('email', 'email', 'trim|required');
        $this->form_validation->set_rules('message', 'Message', 'trim|required');
    }

}

/* End of file Blood_group.php */
/* Location: ./application/controllers/Blood_group.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-06-01 14:53:53 */
/* http://harviacode.com */
